# Generated by Django 3.1.6 on 2021-02-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('payment_way', models.CharField(choices=[('BILLET', 'Billet'), ('CREDIT CARD', 'Credit Card'), ('Debit', 'Debit')], max_length=50)),
                ('signature_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated')], max_length=50)),
                ('plan_type', models.CharField(choices=[('ULTRA', 'Ultra'), ('MEDIUM', 'Medium'), ('BASIC', 'Basic')], max_length=50)),
                ('signature_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('OPEN', 'Open'), ('PAID OUT', 'Paid Out'), ('LATE', 'Late')], max_length=50)),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.finance')),
            ],
        ),
    ]
